# Generated by Django 4.2.7 on 2023-12-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_wallettransaction_coin_delete_wallet_and_more'),
        ('transactions', '0003_delete_transaction'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
