# Generated by Django 4.2.7 on 2023-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('wallet', models.ManyToManyField(to='wallet.wallet')),
                ('wallet_history', models.ManyToManyField(to='wallet.wallettransaction')),
            ],
        ),
    ]
