[package]
name = "test_tokens"
version = "1.0.0"
authors = []

[addresses]
test_coin_admin = '0x5988e8ab6ade6bc3006c7e57992078db2caf981c5a16d53c26cb1071a91b1b26'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
