# Generated by Django 4.2.7 on 2023-12-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('SETTLED', 'Settled')], max_length=10)),
                ('trade_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_coin', to='market.coin')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='users.user')),
                ('sell_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_coin', to='market.coin')),
            ],
        ),
    ]
