# Generated by Django 4.2.7 on 2023-12-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
